import Head from 'next/head'
import { Inter } from 'next/font/google'
import axios from 'axios';
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [name, setName] = useState("");
  const [names, setNames] = useState([]);
  const [update, setUpdate] = useState(false);

  const handleSubmit = (e) =>{
    e.preventDefault();
    
    setUpdate(false)
    axios.post(`/api/set_name`, {name})
    .then((res)=>{
        console.log(res)
        setUpdate(true)
      })
    .catch((err)=>console.log(err))
  }

  useEffect(() => {
    axios.get(`/api/get_name`).then((res)=>{
      setNames(res.data)
    })
  }, [update]);

  return (
    <>
      <Head>
        <title>Deploy to Vercel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form onSubmit={handleSubmit}>
          <input type='text' value={name} onChange={(e)=>setName(e.currentTarget.value)}></input>
          <button type='submit'>Submit</button>
        </form>
        <ul>
          {names.map((n)=>(
            <li key={n._id}>{n.name}</li>
          ))}
        </ul>
      </main>
    </>
  )
}
